### ISSUE TITLE
testando comunicação

### ISSUE THREAD

**Issue by arademaker** [emap-md/main#1]
Pessoal, comentar aqui para eu saber quem recebeu aviso.

**Comment by BrunodePauloAlmeida** [comment]
Recebi.

**Comment by analununes** [comment]
oi

**Comment by reneroliveira** [comment]
oi teste

**Comment by cristhiangrundmann** [comment]
haha git go brrr

**Comment by HannaRF** [comment]
.

**Comment by LucaEscopelli** [comment]
Recebi

**Comment by JPMarciano** [comment]
funcionou

Em qui., 6 de ago. de 2020 às 13:02, Alexandre Rademaker <
notifications@github.com> escreveu:

**Comment by IgorMichels** [comment]
recebido

**Comment by laurachaves** [comment]
Bom dia família

**Comment by Marcos358** [comment]
Chegou

**Comment by danilolc** [comment]
Cada resposta um email

**Comment by dennercrvg** [comment]
recebi

**Comment by yolandadln** [comment]
Recebido

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cadualves** [comment]
Recebido.

**Comment by josearthursouza** [comment]
recebido

**Comment by igorcj** [comment]
recebido

**Comment by carolmcs** [comment]
recebido

Em qui., 6 de ago. de 2020 às 13:02, Alexandre Rademaker <
notifications@github.com> escreveu:
